[package]
name = "aperturec-client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
aperturec-channel = { path = "../channel" }
aperturec-protocol = { path = "../protocol" }
aperturec-state-machine = { path = "../state_machine" }
aperturec-metrics = { path = "../metrics" }
aperturec-trace = { path = "../trace" }
build_id = "0.2.1"
clap = { version = "4.3.22", features = ["derive"] }
cpu-endian = "0.1.1"
ctrlc = "3.4.1"
crossbeam-channel = "0.5.8"
derive_builder = "0.12.0"
flate2 = { version = "1.0", features = ["zlib-ng"], default-features = false }
gethostname = "0.4.3"
gtk = "0.17.1"
rand = "0.8.5"
sysinfo = "0.29.10"
tokio = { version = "1.32.0", features = ["full"] }

[package.metadata.deb]
copyright = "2023, Zetier Inc."
maintainer = "ApertureC Team <aperturec@zetier.com>"
section = "x11"
