[package]
name = "aperturec-client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
aperturec-channel = { path = "../channel" }
aperturec-protocol = { path = "../protocol" }
aperturec-state-machine = { path = "../state_machine" }
build_id = "0.2.1"
clap = { version = "4.3.22", features = ["derive"] }
cpu-endian = "0.1.1"
derive_builder = "0.12.0"
flate2 = "1.0.27"
gethostname = "0.4.3"
gtk = "0.17.1"
log = "0.4.20"
procfs = "0.15.1"
rand = "0.8.5"
simple_logger = "4.2.0"
sys-info = "0.9.1"
tokio = { version = "1.32.0", features = ["full"] }

[package.metadata.deb]
copyright = "2023, Zetier Inc."
maintainer = "ApertureC Team <aperturec@zetier.com>"
section = "x11"
