[package]
name = "aperturec-channel"
version = "0.3.0"
edition = "2021"

[dependencies]
aperturec-protocol = { path = "../protocol" }
aperturec-state-machine = { path = "../state_machine" }
aperturec-metrics = { path = "../metrics" }
aperturec-trace = { path = "../trace" }
anyhow = "1.0"
async-trait = "0.1"
prost = "0.12"
futures = "0.3"
tokio = { version = "1.29", features = ["full"] }
trait-variant = "0.1"
