[package]
name = "aperturec-graphics"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
euclid = "0.22"
image = "0.25"
imageproc = "0.25"
ndarray = { version = "0.16", features = ["rayon"] }
nshare = "0.10"
rayon = "1.10"
