[package]
name = "aperturec-metrics"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = "1.0"
chrono = "0.4.31"
prometheus = { version = "0.13.3", features = ["push"] }
reqwest = "0.12.4"
sysinfo = "0.29.10"
tiny_http = "0.12.0"
tracing = "0.1"

[dev-dependencies]
paste = "1.0"
tempfile = "3.8.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
